package main

import (
	"context"
	"fmt"
	"net/http"

	"github.com/bufbuild/connect-go"
	"github.com/dustin/go-broadcast"
	greetv1 "github.com/trelore/streamingRPC/gen/greet/v1"        // generated by protoc-gen-go
	"github.com/trelore/streamingRPC/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

type GreetServer struct {
	b broadcast.Broadcaster
}

func (s *GreetServer) Greet(
	ctx context.Context,
	req *connect.Request[greetv1.GreetRequest],
) (*connect.Response[greetv1.GreetResponse], error) {

	s.b.Submit(req.Msg.GetName())

	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")
	return res, nil
}

func (s *GreetServer) GreetStream(
	ctx context.Context,
	req *connect.Request[greetv1.GreetStreamRequest],
	stream *connect.ServerStream[greetv1.GreetStreamResponse],
) error {

	ch := make(chan interface{})
	s.b.Register(ch)
	defer s.b.Unregister(ch)

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case name := <-ch:
			stream.Send(&greetv1.GreetStreamResponse{
				People: name.(string),
			})
		}
	}
}

func main() {
	greeter := &GreetServer{
		b: broadcast.NewBroadcaster(10),
	}
	defer greeter.b.Close()
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(greeter)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
